version: "3.9"
services:
  glowesweb:
    build: ./web/
    env_file:
      - ./web/.env
    expose:
      - "80"
    depends_on:
      - glowesapi

  glowesapi:
    build: ./api/
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
    expose:
      - "80"
